### ISSUE TITLE
"Light" OrderDto

### ISSUE THREAD

**Issue by gjrmacedo** [kgrzybek/sample-dotnet-core-cqrs-api#14]
Hi Kamil, thank you for the posts and examples!
I would like to put a scenario to understand your opinion about it.
Imagine that in UI you need a combobox of Orders and the only information needed is Id and Value.
The query is the same that is already done in "GetCustomerOrdersQueryHandler", the only change is that the object that the UI needs has less information.
How would you solve this scenario?
[]'s.

**Comment by kgrzybek** [comment]
I think there is no "best" answer to this question. I would say - be pragmatic :) 

Sometimes I reuse DTO, sometimes I create separate DTO for each use case. 

If my first use case needs 5 fields and second needs 6 fields one DTO sounds better. But if I have one use case when I need 10 fields (for grid) and one use case when I need 2 fields only for combobox I would rather use 2 different DTO's.
